title: "[B|Dev]logs"
description: RandomSoup blog, kind of.
show_excerpts: true

base_url: /posts

minima:
  date_format: "%Y-%m-%d %H:%M"
  skin: dark
  social_links:
    github: RandomSoup

remote_theme: jekyll/minima

include:
 - _pages

exclude: 
 - .gitignore
 - LICENSE
 - README.md
